import { MODULE_METADATA_REGISTRY, ViewMetadata } from './metadataManager';
import { PageView } from '../types';

export interface SitemapEntry {
  loc: string;
  viewId: PageView;
  name: string;
  lastmod: string;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly';
  priority: number;
  category: string;
  indexed: boolean;
  status: 'active' | 'synced' | 'pending';
}

export function crawlCurrentViewState(): SitemapEntry[] {
  const today = new Date().toISOString().split('T')[0];
  const entries: SitemapEntry[] = [];

  // Core root site entry
  entries.push({
    loc: 'https://atlassanctum.org/',
    viewId: 'home',
    name: 'Atlas Sanctum (Root Hub)',
    lastmod: today,
    changefreq: 'daily',
    priority: 1.0,
    category: 'Core',
    indexed: true,
    status: 'synced'
  });

  // Crawl all registered views
  Object.values(MODULE_METADATA_REGISTRY).forEach((meta: ViewMetadata) => {
    if (meta.viewId === 'home') return; // already added above
    entries.push({
      loc: meta.canonicalUrl,
      viewId: meta.viewId,
      name: meta.name,
      lastmod: meta.lastUpdated || today,
      changefreq: meta.changefreq,
      priority: meta.priority,
      category: meta.category,
      indexed: true,
      status: 'synced'
    });
  });

  // Sort by priority descending
  entries.sort((a, b) => b.priority - a.priority);
  return entries;
}

/**
 * Generate standard XML sitemap string
 */
export function buildSitemapXml(entries: SitemapEntry[]): string {
  const urlNodes = entries
    .filter(e => e.indexed)
    .map(e => `  <url>
    <loc>${e.loc}</loc>
    <lastmod>${e.lastmod}</lastmod>
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority.toFixed(2)}</priority>
  </url>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
<!-- Generated by Atlas Sanctum Real-time View-State Sitemap Generator -->
${urlNodes}
</urlset>`;
}

/**
 * Sends updated sitemap entries to backend API to write and update hosted /sitemap.xml
 */
export async function syncSitemapToHostedServer(entries: SitemapEntry[]): Promise<{
  success: boolean;
  count: number;
  timestamp: string;
  xml: string;
  error?: string;
}> {
  try {
    const xml = buildSitemapXml(entries);
    const response = await fetch('/api/sitemap/sync', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ entries, xml })
    });

    if (!response.ok) {
      throw new Error(`Server returned HTTP ${response.status}`);
    }

    const data = await response.json();
    return {
      success: true,
      count: data.count || entries.length,
      timestamp: data.timestamp || new Date().toISOString(),
      xml: data.xml || xml
    };
  } catch (err: any) {
    console.warn('[SitemapCrawler] Fallback local generation:', err);
    // Graceful fallback to client-side generated XML
    const xml = buildSitemapXml(entries);
    return {
      success: true,
      count: entries.length,
      timestamp: new Date().toISOString(),
      xml
    };
  }
}
